apiVersion: batch/v1
kind: Job
metadata:
  name: hostname-job
  namespace: default 
spec:
  template:
    metadata:
      labels:
        app: hostname-app
    spec:
      containers:
      - name: hostname-container
        image: taqiyeddinedj/my-repo:webapp-2.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m" 
      restartPolicy: Never
